#数据库配置
database:
  dbtype: mysql
  host: 202.204.100.175
  port: 3306
  config: charset=utf8mb4&parseTime=True&loc=Local
  dbname: dou_xiao_yin
  username: root
  password: nbroot
#  静态资源路径、请求静态资源的ip和端口
resource:
  staticPath: ./src/public
  #  ip为静态资源所在ip
  ip: 172.20.6.84
  port: 8080